Initial change to terraform version

diff --git a/test b/test
--- a/test
+++ b/test
@@ -13,63 +13,120 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-source globals
-OUTPUTFILE="testoutput.sh"
+# I think it's a good idea to test your scripts. It's kinda awkward but you'll 
+# be happy you did 
+
+
+# DON'T REMOVE FROM test script.
+CYAN='\033[0;36m'
+BCYAN='\033[1;36m'
+NC='\033[0m' # No Color
+DIVIDER=$(printf %"$(tput cols)"s | tr " " "*")
+DIVIDER+="\n"
+
+function get_project_id() {
+    local __resultvar=$1
+    VALUE=$(gcloud config get-value project | xargs)
+    eval $__resultvar="'$VALUE'"
+}
+
+function get_project_number() {
+    local __resultvar=$1
+    local PRO=$2
+    VALUE=$(gcloud projects list --filter="project_id=$PRO" --format="value(PROJECT_NUMBER)" | xargs)
+    eval $__resultvar="'$VALUE'"
+}
+
+# DISPLAY HELPERS
+function section_open() {
+    section_description=$1
+    printf "$DIVIDER"
+    printf "${CYAN}$section_description${NC} \n"
+    printf "$DIVIDER"
+}
+
+function section_close() {
+    printf "$DIVIDER"
+    printf "${CYAN}$section_description ${BCYAN}- done${NC}\n"
+    printf "\n\n"
+}
+
+function evalTest() {
+    local command=$1
+    local expected=$2
+
+    local ERR=""
+    got=$(eval $command 2>errFile)
+    ERR=$(<errFile)
+
+    if [ ${#ERR} -gt 0 ]; then
+        if [ "$expected" = "EXPECTERROR" ]; then
+            printf "Expected Error thrown \n"
+            return
+        fi
+
+        printf "Halting - error: '$ERR'  \n"
+        exit 1
+    fi
+
+    if [ "$got" != "$expected" ]; then
+        printf "Halting: '$got'  \n"
+        exit 1
+    fi
+
+    printf "$expected is ok\n"
+}
+# END DON'T REMOVE FROM test script.
+
+
+
 get_project_id PROJECT
+gcloud services enable cloudresourcemanager.googleapis.com --project=$PROJECT
+get_project_number PROJECT_NUMBER $PROJECT
 REGION=us-central1
-REDISNAME=todo-cache
-randomString SQLSEED
+BASENAME=todo
+SIZE=3
 
-SQLNAME=$PROJECT-db-$SQLSEED
-PASSWORD=password123
-get_project_number  PROJECTNUMBER $PROJECT
+gcloud config set project ${PROJECT}
 
+terraform init
+terraform apply -auto-approve -var project_id="${PROJECT}" -var project_number="${PROJECT_NUMBER}" -var region="${REGION}" -var basename="${BASENAME}" 
 
-printf "\n"
-printf "${BCYAN}Project Details${NC} \n"
-printf "Project ID:         $PROJECT \n"
-printf "Project Number:     $PROJECTNUMBER \n"
-printf "Region:             $REGION \n"
-printf "SQL Server Name:    $SQLNAME \n"
-printf "Redis Server Name:  $REDISNAME \n"
-printf "\n"
-
-./install $PROJECT $REGION $SQLNAME $PASSWORD
 
 section_open "Testing Secrets"
-evalTest 'gcloud secrets describe sqlhost --format="value(name)"' "projects/$PROJECTNUMBER/secrets/sqlhost"
-evalTest 'gcloud secrets describe redishost --format="value(name)"' "projects/$PROJECTNUMBER/secrets/redishost"
+    evalTest 'gcloud secrets describe sqlhost --format="value(name)"' "projects/$PROJECTNUMBER/secrets/sqlhost"
+    evalTest 'gcloud secrets describe redishost --format="value(name)"' "projects/$PROJECTNUMBER/secrets/redishost"
 section_close
 
 section_open "Test Cloud Run Services"
-evalTest 'gcloud run services describe todo-fe --region=$REGION --format="value(name)"' "todo-fe"
-evalTest 'gcloud run services describe todo-api --region=$REGION --format="value(name)"' "todo-api"
+    evalTest 'gcloud run services describe todo-fe --region=$REGION --format="value(name)"' "todo-fe"
+    evalTest 'gcloud run services describe todo-api --region=$REGION --format="value(name)"' "todo-api"
 section_close
 
 section_open "Test SQL Server"
-evalTest 'gcloud sql instances describe $SQLNAME --format="value(name)"' $SQLNAME
+    evalTest 'gcloud sql instances describe $SQLNAME --format="value(name)"' $SQLNAME
 section_close
 
 section_open "Test Redis Server "
-evalTest 'gcloud redis instances describe $REDISNAME --region=$REGION --format="value(name)"' "projects/$PROJECT/locations/$REGION/instances/$REDISNAME"
+    evalTest 'gcloud redis instances describe $REDISNAME --region=$REGION --format="value(name)"' "projects/$PROJECT/locations/$REGION/instances/$REDISNAME"
 section_close
 
 section_open "Testing VPN"
-evalTest 'gcloud compute networks vpc-access connectors describe vpc-connector --region $REGION --format="value(name)"' "projects/$PROJECT/locations/$REGION/connectors/vpc-connector"
-evalTest 'gcloud compute addresses describe google-managed-services-vpn-connector --global --format="value(name)"' "google-managed-services-vpn-connector"
+    evalTest 'gcloud compute networks vpc-access connectors describe vpc-connector --region $REGION --format="value(name)"' "projects/$PROJECT/locations/$REGION/connectors/vpc-connector"
+    evalTest 'gcloud compute addresses describe google-managed-services-vpn-connector --global --format="value(name)"' "google-managed-services-vpn-connector"
 section_close
 
 # This is a bug. Everytime this command runs "Encryption: Google Managed Key gets thrown in STDERR"
 section_open "Testing Artifact Registry repoistory for containers"
-evalTest 'gcloud artifacts repositories describe todo-app --location $REGION --format="value(name)"' "EXPECTERROR"
+    evalTest 'gcloud artifacts repositories describe todo-app --location $REGION --format="value(name)"' "EXPECTERROR"
 section_close
 
-
+terraform destroy -auto-approve -var project_id="${BASENAME}" -var project_number="${PROJECT_NUMBER}" -var region="${REGION}" -var basename="${BASENAME}" 
 ./uninstall $PROJECT $REGION $SQLNAME 
 
-section_open "Waiting for Redis Server to be deleted"
-await_command state 5 60 "redisGone" $REDISNAME $REGION
-section_close
+# section_open "Waiting for Redis Server to be deleted"
+# await_command state 5 60 "redisGone" $REDISNAME $REGION
+# section_close
 
 
 section_open "Testing Secrets"
